[build]
  command = "npm run build:static"
  publish = "dist"

[build.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/.puppeteer"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
